### ISSUE TITLE
Identifo Admin: External services issue with SES

### ISSUE THREAD

**Issue by kazemisoroush** [MadAppGang/identifo#176]
The email service type cannot be set through the UI or `server-config.yaml` file due to an invalid service type error. The validation expects to get `ses` but when it's trying to save the service it expects to see `aws ses` which is a small conflict in saving and using it. Detailed explanation in this video:
https://www.loom.com/share/db086e9ea2464bee8516b4ee2c9eed17

**Comment by erudenko** [comment]
https://github.com/MadAppGang/identifo/releases/tag/v2.1.0
