### ISSUE TITLE
Identifo Admin: Edit application via UI is not working as expected

### ISSUE THREAD

**Issue by kazemisoroush** [MadAppGang/identifo#178]
When I try to edit an application from UI, it's not working as expected. Especially, with the registration and activate toggles. Please have a look at this video explaining the situation:
https://www.loom.com/share/6bb67e2478f04379957814624fce2eb1

**Comment by kazemisoroush** [comment]
When I edit those toggles directly from Database, they take effect in UI though.

**Comment by erudenko** [comment]
https://github.com/MadAppGang/identifo/releases/tag/v2.1.0
