### ISSUE TITLE
Identifo Element: Respect login type from app settings

### ISSUE THREAD

**Issue by kazemisoroush** [MadAppGang/identifo#180]
If the `loginWith` option is disabled and we try to login through the `/web/login` page, it won't allow us to login because the form only accepts email but the application won't allow email. Please have a look into this video:
https://www.loom.com/share/a3b0c24e5ea34110b5720e6b5c61d0ee

**Comment by kazemisoroush** [comment]
![image](https://user-images.githubusercontent.com/8931595/130001051-9dd3c9c1-da82-4c34-bdde-e761647115f2.png)
![image](https://user-images.githubusercontent.com/8931595/130001071-a4146181-ae49-4875-852c-5a460b19592b.png)
![image](https://user-images.githubusercontent.com/8931595/130001086-7300fbda-220b-4cea-aead-51ae0e4036c2.png)

**Comment by sokolovstas** [comment]
We need to check login types and change element behavior on login/register/forgot password pages

**Comment by erudenko** [comment]
https://github.com/MadAppGang/identifo/releases/tag/v2.1.0

**Comment by kazemisoroush** [comment]
This issue still exists in v2.1.1
https://www.loom.com/share/dbdcc42fdcab4c6396c8e63a0b86a03f
