### ISSUE TITLE
Identifo allow registration not reflected on the web login page

### ISSUE THREAD

**Issue by kazemisoroush** [MadAppGang/identifo#181]
If we disable these 2 options from an application, we are disabling the user access to any signup or registration views:
1. Allow Registration
2. Allow Anonymous Registration

But in this case, although I disabled them like so:
![image](https://user-images.githubusercontent.com/8931595/130002467-663fac98-b4da-4cad-b697-a2ef1082d3f4.png)

I still can see the signup link on the web login page:
![image](https://user-images.githubusercontent.com/8931595/130002488-5bf06939-40b6-41cc-99b4-6a86a6f402a2.png)

Actual behavior:
The `Don't have an account? Sign Up` text is visible on the web login page.

Expected behavior:
The text `Don't have an account? Sign Up` should not be visible to the user as the registration is not allowed.

**Comment by kazemisoroush** [comment]
This also should be covered for the "Forgot Password" functionality too:
![image](https://user-images.githubusercontent.com/8931595/130016720-f2c56af9-ac01-44a4-9d57-2e418c2ecf83.png)

The login type should reflect forget password as well:
![image](https://user-images.githubusercontent.com/8931595/130016893-33883f64-73bc-49cb-994b-c6cbf50b713f.png)

**Comment by sokolovstas** [comment]
Second part of this bug will be fixed in #180

**Comment by kazemisoroush** [comment]
https://www.loom.com/share/dbdcc42fdcab4c6396c8e63a0b86a03f
