### ISSUE TITLE
Identifo Admin: Static file configuration is not filled out from server-config.yaml file

### ISSUE THREAD

**Issue by kazemisoroush** [MadAppGang/identifo#186]
Static file configuration won't get reflected by the `server-config.yaml` file coming from S3:

![image](https://user-images.githubusercontent.com/8931595/130014514-dc6ffece-fc6d-43d1-ad78-5aa9ba1aa8f2.png)
![image](https://user-images.githubusercontent.com/8931595/130014535-f2774819-7d92-4037-b619-311414826b4b.png)

Please have a look at this video stating the issue:
https://www.loom.com/share/b609c23432b34d0283585918d1e6d972

**Comment by kazemisoroush** [comment]
This may not be as critical as others. It's kinda nice to have.

**Comment by kazemisoroush** [comment]
Same thing happens in "Server Settings" menu under "Server" main menu in the admin panel:
![image](https://user-images.githubusercontent.com/8931595/130014725-4d296157-1fdc-4966-a36b-2e938c6e5e31.png)

**Comment by erudenko** [comment]
Fixed in version 2.1.0
https://github.com/MadAppGang/identifo/releases/tag/v2.1.0
