### ISSUE TITLE
error creating PEM: x509: unsupported public key type: <nil>

### ISSUE THREAD

**Issue by kazemisoroush** [MadAppGang/identifo#210]
This is happening on Identifo v2.1.1. A `500` error happens when logging in to the admin panel. After logging into the admin panel an error snack bar will appear like so:
![image](https://user-images.githubusercontent.com/8931595/133347992-037e6db2-1a91-4eee-ac25-89c9f82ad89c.png)

Here is a complete request and response:
```
{
    "error": "error creating PEM: x509: unsupported public key type: <nil>",
    "code": 500
}
```
Request:
![image](https://user-images.githubusercontent.com/8931595/133348060-f3c3b667-4382-4a41-b387-d77ddc7d517a.png)

Response Headers:
![image](https://user-images.githubusercontent.com/8931595/133348077-c83dc71a-ec84-48d4-aa0d-8b3323e6b51e.png)

Request Headers:
![image](https://user-images.githubusercontent.com/8931595/133348093-f48da05e-9ed9-4bb0-93bd-f909238b4115.png)

Query Parameters:
![image](https://user-images.githubusercontent.com/8931595/133348121-4997a781-8701-4cb6-a205-d56fd3ec2c9d.png)

**Comment by erudenko** [comment]
Fixed in `V2.1.2`
