### ISSUE TITLE
Identifo: Login with email and password doesn't work

### ISSUE THREAD

**Issue by kazemisoroush** [MadAppGang/identifo#211]
https://www.loom.com/share/01de6cc0a7cb4a4580c2b4257824c09c

The problem is either in update the password in admin or in password hash check in `/auth/login` API.

**Comment by kazemisoroush** [comment]
The problem is with the Identifo v2.1.1

**Comment by erudenko** [comment]
@kazemisoroush thanks for reporting.

**Comment by erudenko** [comment]
It is fixed in v2.1.3
