### ISSUE TITLE
Identifo Admin: Public key is not recognized from server config file

### ISSUE THREAD

**Issue by kazemisoroush** [MadAppGang/identifo#215]
@Jack Rudenko found the issue. The problem is not with the public/private key pair. It’s with the settings parser. The public_key_key is removed from settings:
![image](https://user-images.githubusercontent.com/8931595/133386478-dd82d9bc-59b1-4aff-a276-e8659ac8a62f.png)

https://www.loom.com/share/5e8bd08fb8c34887a037ae48138378cc

It’s been removed in this commit:
https://github.com/MadAppGang/identifo/commit/d1a92bb60f128c1c20b9621af127ad399e2e4dbe

So, currently, there is no way to introduce or generate a public key to Identifo.

Also, when I try "Generate Key" it also doesn't work:
![image](https://user-images.githubusercontent.com/8931595/133386783-bf3eae33-2987-4b47-a13e-a6fa6f952642.png)

Here's the response:
```
{
    "error": "error creating PEM: x509: unsupported public key type: <nil>",
    "code": 500
}
```

**Comment by erudenko** [comment]
Fixed in version `v2.1.2`
