### ISSUE TITLE
Identifo Admin: Registration doesn't work as expected

### ISSUE THREAD

**Issue by kazemisoroush** [MadAppGang/identifo#220]
https://www.loom.com/share/c2486ed11852404eba3c5555b198d8cd

**Comment by kazemisoroush** [comment]
This is happening in v2.1.2

**Comment by kazemisoroush** [comment]
Found the issue. The registration API fails to store the username. That is why the admin panel won't show the user in its list and login says "user not found". At least this is one reason.

**Comment by erudenko** [comment]
@kazemisoroush the issue is not longer valid
