### ISSUE TITLE
Identifo Admin: Pagination on the users page

### ISSUE THREAD

**Issue by kazemisoroush** [MadAppGang/identifo#235]
When a system has many users (e.g. more than 200 users) it's hard to manage them in the admin panel without a pagination:
![image](https://user-images.githubusercontent.com/8931595/135030307-d6a01a55-d94f-4188-a130-cbd92dd0893a.png)

**Comment by erudenko** [comment]
@kazemisoroush we are not supporting it yet, and we don't have plans to do it. 
Instead the search is available.
