### ISSUE TITLE
useless replace directive in go.mod

### ISSUE THREAD

**Issue by Morty-luo** [MadAppGang/identifo#383]
It seems that `MadAppGang/identifo` does not depend on `github.com/sfreiberg/gotwilio` any more, both directly and indirectly. 
So, replace directive left in go.mod makes no sense. Should it be dropped?
```text
replace github.com/sfreiberg/gotwilio => github.com/MadAppGang/gotwilio v0.0.0-20210820024906-f91dd2ebe762
```

**Comment by hummerd** [comment]
Thanks! Will be removed in https://github.com/MadAppGang/identifo/pull/384

**Comment by hummerd** [comment]
Done
